import React from 'react'
import Button from './Button'

const NumberGrid = (props) => {
    return (
        <div>
        <table className="calculator">
            <tbody>
            <tr>
                <td>
                    <Button
                        text="C/AC"
                        handleClick={props.handleClick}
                        value="clear"
                        classes="sm-text btn-clear"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="MU"
                        handleClick={props.handleClick}
                        value="mu"
                        classes="sm-text"
                        disabled={true}
                    />
                </td>
                <td>
                    <Button
                        text="%"
                        handleClick={props.handleClick}
                        value="%"
                        disabled={true}
                    />
                </td>
                <td>
                    <Button
                        text="/"
                        handleClick={props.handleClick}
                        value="divide"
                        disabled={false}
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <Button
                        text="7"
                        handleClick={props.handleClick}
                        value="7"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="8"
                        handleClick={props.handleClick}
                        value="8"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="9"
                        handleClick={props.handleClick}
                        value="9"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="x"
                        handleClick={props.handleClick}
                        value="multiply"
                        disabled={false}
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <Button
                        text="4"
                        handleClick={props.handleClick}
                        value="4"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="5"
                        handleClick={props.handleClick}
                        value="5"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="6"
                        handleClick={props.handleClick}
                        value="6"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="-"
                        handleClick={props.handleClick}
                        value="subtract"
                        disabled={false}
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <Button
                        text="1"
                        handleClick={props.handleClick}
                        value="1"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="2"
                        handleClick={props.handleClick}
                        value="2"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="3"
                        handleClick={props.handleClick}
                        value="3"
                        disabled={false}
                    />
                </td>
                <td rowSpan="2">
                    <Button
                        text="+"
                        handleClick={props.handleClick}
                        value="add"
                        classes="span2"
                        disabled={false}
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <Button
                        text="0"
                        handleClick={props.handleClick}
                        value="0"
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="."
                        handleClick={props.handleClick}
                        value="."
                        disabled={false}
                    />
                </td>
                <td>
                    <Button
                        text="="
                        handleClick={props.handleClick}
                        value="total"
                        disabled={false}
                    />
                </td>
            </tr>
            </tbody>
        </table>
        </div>
    )
}

export default NumberGrid
